---
- hosts: all
  gather_facts: no 
  vars:
  
    user: username

    home_dirs:
      - "/home/{{user}}/"
      - "/root/"

    packages:
      - nmap
      - bash-completion
      
    to_bashrc:
      - 'PS1=''\[\e]0;\u@\h: \w\a\]${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '''
      - "alias vi=vim"
      - "alias ll='ls -lF'"
      - "alias la='ls -aF'"
      - "alias lal='ls -alF'"
      - "alias sudo='sudo '"
      - "cd /home/{{ user }}"

    to_vimrc:
      - "autocmd FileType yaml setlocal ts=2 sts=2 sw=2 expandtab"
      - "set autoindent"

    to_profiled:
    - "export EDITOR=vim"
    - "export LESS='-Ri'"

  tasks:

    - name: "installing {{ packages | join(' ') }}"
      yum:
        name: "{{ packages }}"
        state: latest

    - name: adding to .bashrc's
      lineinfile:
        path: "{{ item[0] }}.bashrc"
        state: present
        line: "{{ item[1] }}"
      loop:
        "{{ home_dirs | product(to_bashrc) | list }}"
    
    - name: adding to .vimrc's
      lineinfile:
        create: yes
        path: "{{ item[0] }}.vimrc"
        state: present
        line: "{{ item[1] }}"
      loop:
        "{{ home_dirs | product(to_vimrc) | list }}"

    - name: adding to /etc/profile.d/ansible.sh
      lineinfile:
        path: /etc/profile.d/ansible.sh
        state: present
        create: yes
        line: "{{ item }}"
      loop: "{{ to_profiled }}"

    - name: "adding {{ user }} to /etc/sudoers"
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^{{ user }}\s'
        line: "{{ user }} ALL=(ALL:ALL) NOPASSWD: ALL"
...
