---
- hosts: all
  gather_facts: no
  become: yes
  vars:

    users:
      - user
      - root

    packages:
      - nmap
      - bash-completion
      - tree
      - vim

    to_bashrc: |
      PS1='\[\e]0;\u@\h: \w\a\]${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
      alias vi=vim
      alias la='ls -aF'
      alias ll='ls -lhF'
      alias lal='ls -alhF'
      alias sudo='sudo '
      alias k=kubectl

    to_vimrc: |
      autocmd FileType yaml setlocal ts=2 sts=2 sw=2 expandtab
      autocmd FileType python setlocal ts=4 sts=4 sw=4 expandtab
      autocmd FileType js setlocal ts=4 sts=4 sw=4 expandtab
      set autoindent

    to_profiled: |
      export EDITOR=vim
      export LESS='-Ri'

  tasks:

    - name: "installing {{ packages | join(', ') }}"
      package:
        name: "{{ packages }}"
        state: latest

    - name: adding to .bashrcs
      blockinfile:
        create: yes
        path: "~/.bashrc"
        state: present
        block: "{{ to_bashrc }}"
      become: yes
      become_user: "{{ item }}"
      loop: "{{ users }}"

    - name: adding to .vimrcs
      blockinfile:
        create: yes
        path: "~/.vimrc"
        state: present
        block: "{{ to_vimrc }}"
        marker: "\"{mark} ANSIBLE MANAGED BLOCK"
      become: yes
      become_user: "{{ item }}"
      loop: "{{ users }}"

    - name: adding to /etc/profile.d/ansible.sh
      copy:
        content: "{{ to_profiled }}"
        dest: /etc/profile.d/ansible.sh
        force: yes

    - name: "adding {{ users | join(', ') }} to /etc/sudoers"
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^{{ item }}\s'
        line: "{{ item }} ALL=(ALL:ALL) NOPASSWD: ALL"
      loop: "{{ users }}"
...
